name: "Test"
on:
  workflow_dispatch:
    
jobs:
  build_on_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up environment variables
        run: |
          $env:APK_SIGN_PWD="${{ secrets.APK_SIGN_PWD }}"
          $env:APK_SIGN_ALIAS="${{ secrets.APK_SIGN_ALIAS }}"
          $env:APK_SIGN_JKS="${{ secrets.APK_SIGN_JKS }}"
          echo "APK_SIGN_PWD length: $($env:APK_SIGN_PWD.Length)"
          echo "APK_SIGN_ALIAS length: $($env:APK_SIGN_ALIAS.Length)"
          echo "APK_SIGN_JKS length: $($env:APK_SIGN_JKS.Length)"
        shell: pwsh

      - name: Write signing properties
        run: |
          echo keyPassword=$env:APK_SIGN_PWD > android\key.properties
          echo storePassword=$env:APK_SIGN_PWD >> android\key.properties
          echo keyAlias=$env:APK_SIGN_ALIAS >> android\key.properties
          echo storeFile=key.jks >> android\key.properties
        shell: pwsh

      - name: Decode and save key
        run: |
          echo $env:APK_SIGN_JKS | base64 -d > android\app\key.jks
        shell: pwsh

      - name: Generate and print hash of key.properties
        run: |
          $keyPropertiesHash = Get-FileHash -Path android\key.properties -Algorithm SHA256
          echo "key.properties hash: $($keyPropertiesHash.Hash)"
        shell: pwsh

      - name: Generate and print hash of key.jks
        run: |
          $keyJksHash = Get-FileHash -Path android\app\key.jks -Algorithm SHA256
          echo "key.jks hash: $($keyJksHash.Hash)"
        shell: pwsh
