name: "BUILD"
on:
  workflow_dispatch:
    
jobs:
  build_on_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up environment variables
        run: |
          $env:APK_SIGN_PWD="${{ secrets.APK_SIGN_PWD }}"
          $env:APK_SIGN_ALIAS="${{ secrets.APK_SIGN_ALIAS }}"
          $env:APK_SIGN_JKS="${{ secrets.APK_SIGN_JKS }}"
          echo "APK_SIGN_PWD length: $($env:APK_SIGN_PWD.Length)"
          echo "APK_SIGN_ALIAS length: $($env:APK_SIGN_ALIAS.Length)"
          echo "APK_SIGN_JKS length: $($env:APK_SIGN_JKS.Length)"
        shell: pwsh

